### ISSUE TITLE
Whiter text for "Rounded QS & Notifications (Android Pie Style)"

### ISSUE THREAD

**Issue by Pentadome** [ohayoubaka/yoru.#6]
Hello,

First i would like to thank you for this amazing theme, I really like it however I just got one problem. For me, the text in the notifications when you use Rounded QS & Notifications (Android Pie Style) for system ui headers,  is a bit to dark. I tried to make it brighter myself but the only thing I managed to do is getting errors lol. 

Could we get an option for lighter text when using this notification style? I'm sorry if this is not the right place for requests like this. 

Thanks for your time!

edit: forgot to mention, im using black notification color

**Comment by ohayoubaka** [comment]
Rounded QS & Notifications overlay does not affect notification text colours, so I'm not sure what your issue is about really.

**Comment by Pentadome** [comment]
http://imgur.com/gallery/ee16zOW

Sorry if I am confusing, this is how my notifications look like, is there anything I can. Do about that?

**Comment by ohayoubaka** [comment]
It looks like you forgot to select black notification colour option for Android System overlay.

**Comment by emyarod** [comment]
@ohayoubaka Even with black notification color option selected, it seems some apps hard code their notification text colors. Would it be possible to add a drop shadow to all text in black notifications, similar to [Swift](https://play.google.com/store/apps/details?id=com.brit.swiftinstaller&hl=en_US)? Screenshot below:

![image](https://user-images.githubusercontent.com/8265238/45129987-4f3f9d00-b14c-11e8-91e7-add52e66c5d6.png)

**Comment by ohayoubaka** [comment]
@emyarod thanks for bringing that function to my attention, I will consider adding such a function to the theme in a future update.

**Comment by ohayoubaka** [comment]
Added in the latest update as an option in the Android System overlay, try and give it a go.

**Comment by emyarod** [comment]
so far so good! awesome work @ohayoubaka 

![image](https://user-images.githubusercontent.com/8265238/45597411-a84fd200-b991-11e8-88e3-fb98b0ebfa45.png)

**Comment by ohayoubaka** [comment]
Thanks! Looks like this issue's solved then.
